# Generated by Django 3.2.16 on 2022-12-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_perfil_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='login/perfil/'),
        ),
    ]
