# Generated by Django 3.2.16 on 2022-12-24 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_productos_categoria'),
        ('login', '0003_alter_perfil_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.productos')),
            ],
        ),
    ]
