# Generated by Django 3.2.16 on 2022-12-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_carrito_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoproducts',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
