# Generated by Django 3.2.16 on 2022-12-31 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_carritoproducts_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='img',
        ),
    ]
