# Generated by Django 3.2.16 on 2022-12-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='oferta_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
