# Generated by Django 3.2.16 on 2022-12-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221218_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
