# Generated by Django 3.2.16 on 2022-12-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_productos_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='oferta_active',
        ),
        migrations.AlterField(
            model_name='productos',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='home/imgs'),
        ),
    ]
