# Generated by Django 3.2.16 on 2022-12-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221219_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='home/imgs/'),
        ),
    ]
