# Generated by Django 3.2.16 on 2022-12-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_productos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ManyToManyField(related_name='categorias', to='home.Categorias'),
        ),
    ]
